### PR TITLE
fixed token info view value font style #1767

### LINKED ISSUE #1767: Add Portfolio, Performance, Stats to all ERC20 tokens & Ether [Samoa]
**Portfolio**
* Balance
* 24H Return
* Portfolio Share
* Profit/Loss
* Average Cost
* Paid Fees

**Performance**
* 1D
* 1 Week
* 1 Month
* 3 Months
* 1 Year

**Stats:**
* Market Cap
* Total Supply
* Max Supply
* 1 Year High
* 1 Year Low

Zeplin:
https://zpl.io/bJoq3L3
https://zpl.io/aNN0AyZ
https://zpl.io/Vk458mv

Screenshot 2021-03-10 at 15 15 16

### PR DESCRIPTION
**Pull request by mpaschenko**
Closes #1767

### CODE REVIEW

File: app/src/main/java/com/alphawallet/app/widget/TokenInfoView.java [hunk 1]
```diff
@@ -56,7 +57,8 @@ public void setCurrencyValue(double v)
     {
         value.setVisibility(View.VISIBLE);
         valueLongText.setVisibility(View.GONE);
-        value.setText(TickerService.getFullCurrencyString(v));
+        String prefix = hasPrefix ? (v > 0 ? "+" : "") : "";
```
Comment (seabornlee) [inline app/src/main/java/com/alphawallet/app/widget/TokenInfoView.java:60]: Is is equal to `hasPrefix && v > 0 ? "+" : ""`

**Review by JamesSmartCell — APPROVED** [review]
