### PR TITLE
Fix Event Sync

### LINKED ISSUE #3078: Event Sync fail
On certain chains (Polygon esp) the event sync is not working correctly.

Further, the limit discovery system appears to be blocking.

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Fixes an issue where esp Polygon event sync failed on two counts:
- Batch event fetch fails (add system where we dynamically track and cache failure to fetch batch array format).
- Sync size wasn't being allowed to dynamically change if an incorrect limit is applied.

Fixes #3078

### CODE REVIEW

File: app/src/main/java/com/alphawallet/app/entity/EventSync.java [hunk 1]
```diff
@@ -174,7 +174,7 @@ private BigInteger adjustForLimitedBlockSize(BigInteger eventReadStartBlock, Big
 
     public boolean handleEthLogError(Response.Error error, DefaultBlockParameter startBlock, DefaultBlockParameter endBlock, SyncDef sync, Realm realm)
     {
-        if (error.getCode() == -32005)
+        if (error.getCode() == -32005 || error.getCode() == -32600)
```
Comment (seabornlee) [inline app/src/main/java/com/alphawallet/app/entity/EventSync.java:177]: I suggest extracting constants or adding comments to express the errors they are dealing with.

**Review by seabornlee — APPROVED** [review]
